# Generated by Django 4.1.6 on 2023-02-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientcategory'),
        ),
        migrations.CreateModel(
            name='TheMealDBMeal',
            fields=[
                ('themealdb_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.meal')),
            ],
        ),
        migrations.CreateModel(
            name='TheMealDBIngredient',
            fields=[
                ('themealdb_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
    ]
