# Generated by Django 4.1.6 on 2023-02-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_category_themealdbmeal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheMealDBIngredientCategory',
            fields=[
                ('temealdb_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientcategory')),
            ],
        ),
    ]
