# Generated by Django 4.1.6 on 2023-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_themealdbingredientcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='small_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='small_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
