# Generated by Django 4.1.6 on 2023-02-06 15:20

from django.db import migrations


class MySQLOnlyRunSQL(migrations.RunSQL):

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor.startswith('mysql'):
            super().database_backwards(app_label, schema_editor, from_state, to_state)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor.startswith('mysql'):
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_ingredient_small_image_url_meal_small_image_url'),
    ]

    operations = [
        MySQLOnlyRunSQL(
            sql=('CREATE FULLTEXT INDEX meal_name_index ON recipes_meal (name)',),
            reverse_sql=('DROP INDEX meal_name_index ON recipes_meal',)
        )
    ]
